Module : Data Structure Assignment



Problem Statement:


You work in XYZ Corporation as a Data Analyst. Your corporation has told you to work with the 
structure of the Data.
Tasks to be performed:

    
1. Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True, 8.10.

a. Now in the ‘myList’, append these values: 30,40 
b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’
2. Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.
a. After that eliminate the ‘text’ value form the dictonary.
b. Add ‘features’ in the dictonary.
c. Fetch the ‘data’ element from the dictonary and display it in the output.


In [17]:
myList = [10,20,30,"apple", True, 8.10]

In [18]:
myList.extend([30,40])
myList

[10, 20, 30, 'apple', True, 8.1, 30, 40]

In [19]:
reversedList = myList[::-1]
print(reversedList)

[40, 30, 8.1, True, 'apple', 30, 20, 10]


In [38]:
Dict = {1: 'data', 2: 'information', 3: 'text'}
print(Dict[1])
Dict.pop(3)
Dict[3] = 'features'
print(Dict)

data
{1: 'data', 2: 'information', 3: 'features'}


In [39]:
print(Dict[1])

data


3. Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [45]:
my_tuple = (1, 2, 3, 'apple', 'mango')

tuple

In [ ]:
4. Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50
a. Find the minimum value from the numeric_tuple.
b. Concatenate my_tuple with numeric_tuple and store the result in r1.
c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.


In [48]:
numeric_tuple = (10, 20, 30 ,40, 50)
min(numeric_tuple)

10

In [51]:
r1 = my_tuple + numeric_tuple
print(r1)

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)


In [58]:
newdupil = ((my_tuple) * 2)
print(newdupil)

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


In [ ]:
5. Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to 
contains{2,3,7,6,1}
a. Perform the below operation:
a. set1 union set2
b. set1 intersection set2 
c. set1 difference set2

In [61]:
set1 = {1,2,3,4,5}
set2 = {2,3,7,6,1}
union = set1.union(set2)
intersection = set1.intersection(set2)
diff = set1 - set2
print(union, intersection, diff)

{1, 2, 3, 4, 5, 6, 7} {1, 2, 3} {4, 5}


Module 4: Numpy Assignment


Problem Statement:

You work in XYZ Corporation as a Data Analyst. Your corporation has told you to use the numpy 
package and do some tasks related to that:

Tasks to be performed:
1. Create a 3x3 matrix array with values ranging from 2 to 10.


In [1]:
import numpy as np
x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


2. Create a numpy array having user input values and convert the integer type to the float type 
of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]


In [13]:
arr = np.array([])
a=int(input("Size of array:"))
for i in range(a):
    x=int(input("Element:"))
    arr = np.append(arr, [x])


Size of array:3
Element:1
Element:2
Element:3


In [16]:
arr2 = arr.astype(np.float)
print(arr2)

[1. 2. 3.]


<ipython-input-16-6eb62b0ca1f8>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr2 = arr.astype(np.float)


In [ ]:
3. Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [17]:
my_array = np.array([10,20,30])

In [18]:
np.append(my_array, (40,50,60,70,80,90))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
4. Create two numpy arrays and add the elements of both the arrays and store the result in 
sumArray.


In [26]:
a1 = np.array([1, 2, 3])
a2 = np.array([3, 4, 5])
sumArray = np.add(a1, a2)
sumArray

array([4, 6, 8])

In [ ]:
5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array

In [30]:
array1 = [[30*y + 10*x for x in range(1, 4)] for y in range(3)]
print(x)

print(x[:1])
print(x[2][2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20 30]]
90


In [ ]:
Module 4: Numpy Assignment
Problem Statement:
You work in XYZ Company as a Python. The company officials want you to build a python program.
Tasks to be performed:
1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]


In [2]:
import numpy as np

def solve(dim_tuple,fillnumber):

    return np.full(dim_tuple,fillnumber)

x= solve((3,3),5)

print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
2. Create a method that takes n Numpy arrays of same dimensions sums them and return the 
answer.


In [16]:
import numpy as np
def sumarr(n,a,b):
    sum = np.zeros((a,b))
    for i in range(0, n):
        arr = np.random.randint(10, 50, (a,b))
        print(arr)
        sum = sum + arr
    
    return sum
    
    
n= int(input("Enter no. of arrays you wish to take: "))
a = int(input("Enter no. of rows here: "))
b = int(input("Enter no. of columns here: "))
sumarr(n,a,b)

Enter no. of arrays you wish to take: 2
Enter no. of rows here: 2
Enter no. of columns here: 2
[[48 27]
 [37 29]]
[[27 15]
 [45 14]]


array([[75., 42.],
       [82., 43.]])

In [10]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr1+arr2

array([ 6,  8, 10, 12])

In [61]:
ar = np.array([[1, 2, 3], [4, 5, 6]])

def main():
    N = int(input("enter row: "))
    M = int(input("enter column: "))
    print(ar[0:N, 0:M])

main()
    

enter row: 2
enter column: 2
[[1 2]
 [4 5]]


In [ ]:
3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M. The method should return the top-left N X M sub matrix e.g:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
top_left_sub_matrix (matrix, 2, 2) -> should return:
 [
 [1, 2]
 [4, 5]
 ]



In [62]:
ar = np.array([[1, 2, 3], [4, 5, 6]])

def main():
    N = int(input("enter row: "))
    M = int(input("enter column: "))
    print(ar[0:N, 0:M])

main()

enter row: 2
enter column: 2
[[1 2]
 [4 5]]


In [ ]:
4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]


In [72]:
ar2 = np.array([
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ])
#here
N = 3
M = 3
def main():
    n = int(input("enter row: "))
    m = int(input("enter column: "))
    print(ar[n:, m:])
    
main()


enter row: 1
enter column: 0
[[4 5 6]]


5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method 
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's 
standard deviation as values:
 [1, 1, 1]
solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0}

In [3]:
import numpy as np
def main():
    a = np.array([1,3,5,6,7])
    
    m = np.mean(a)
    s = np.std(a)
    dict = {'mean': m , 'std_dev': s}
    print(dict)
    
    
a = np.array([1,3,5,6,7])
main()
    
    

{'mean': 4.4, 'std_dev': 2.1540659228538015}
